# @package _global_

dataset_path: ${work_dir}/data/slakh2100/test
separation_dir: ${work_dir}/output/separations/msdm-gaussian
separation:
  _target_: evaluation.experiments.separate_slakh_msdm
  _partial_: True 
  model_path: ${work_dir}/ckpts/avid-darkness-164/epoch=419-valid_loss=0.014.ckpt
  s_churn: 40.0
  gamma: 0.75
  num_steps: 150
  batch_size: 32  # < Change to best fit your architecture
  num_resamples: 2
  use_gaussian: True